#! /bin/bash
# Creates IPA file with dSYMs. Builds the project, archives, signs and exports.
# Author: Tomasz Szulc (http://szulctomasz.com | http://twitter.com/tomkowz)

# make_ipa -w "name.xcworkspace" -s "scheme" -c "configuration" -p "provisioning_profile_name"

while getopts ":w:s:p:c:" opt; do
	case $opt in
	  w) workspace=$OPTARG >&2;;
	  
	  s) scheme=$OPTARG >&2;;

	  c) configuration=$OPTARG >&2;;

	  p) provisioning=$OPTARG >&2;;
	  
	  \?)
	    echo "Invalid option: -$OPTARG" >&2
	    exit 1;;
	  
	  :)
	    echo "Option -$OPTARG requires an argument." >&2
	    exit 1;;
	esac
done

rm -rf build

xcodebuild clean -workspace "$workspace" -scheme "$scheme" -configuration "$configuration"
xcodebuild archive -workspace "$workspace" -scheme "$scheme" -archivePath "build/$scheme.xcarchive"
xcodebuild -exportArchive -archivePath "build/$scheme.xcarchive" -exportPath "build/$scheme.ipa" -exportFormat ipa -exportProvisioningProfile "$provisioning"
zip -r build/$scheme-dSym.zip build/$scheme.xcarchive/dSyms
